version: "3"
services:
  mongo:
    image: mongo
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo:/data/db
    container_name: clean-archi-go-mongo
